# Generated by Django 3.0.7 on 2021-06-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0002_remove_order_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='img', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
