# Generated by Django 3.2.4 on 2021-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0002_auto_20210620_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='const',
            field=models.BooleanField(default=False),
        ),
    ]
