# Generated by Django 3.2.4 on 2021-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0004_auto_20210620_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gammes',
            old_name='engineer_high_end',
            new_name='engineer_avg',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='engineer_low_end',
            new_name='engineer_gpu_clock_speed',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='programmer_high_end',
            new_name='engineer_max',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='programmer_low_end',
            new_name='engineer_menimum',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='programmer_mediuum',
            new_name='programmer_multi_64_bit',
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_multi_core',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_performance_physics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_sigle_core',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
