# Generated by Django 3.2.3 on 2021-06-06 17:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0004_auto_20210606_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
