# Generated by Django 3.2.4 on 2021-06-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0005_auto_20210620_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('li', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gamme_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gammer_high_end', models.PositiveIntegerField(default=0)),
                ('gammer_medium', models.PositiveIntegerField(default=0)),
                ('gammer_low_end', models.PositiveIntegerField(default=0)),
                ('engineer_menimum', models.PositiveIntegerField(default=0)),
                ('engineer_avg', models.PositiveIntegerField(default=0)),
                ('engineer_medium', models.PositiveIntegerField(default=0)),
                ('engineer_max', models.PositiveIntegerField(default=0)),
                ('engineer_gpu_clock_speed', models.PositiveIntegerField(default=0)),
                ('programmer_sigle_core', models.PositiveIntegerField(default=0)),
                ('programmer_multi_core', models.PositiveIntegerField(default=0)),
                ('programmer_multi_64_bit', models.PositiveIntegerField(default=0)),
                ('programmer_performance_physics', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tech_Parts.games')),
            ],
        ),
        migrations.DeleteModel(
            name='Gammes',
        ),
    ]
