# Generated by Django 3.2.4 on 2021-06-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0006_auto_20210620_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamme_Type',
            new_name='Games_Type',
        ),
    ]
