# Generated by Django 3.0.7 on 2021-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0007_gammes_li'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammes',
            name='li',
            field=models.CharField(max_length=100),
        ),
    ]
