# Generated by Django 3.2.4 on 2021-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0007_rename_gamme_type_games_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games_type',
            old_name='gammer_high_end',
            new_name='gamer_high_end',
        ),
        migrations.RenameField(
            model_name='games_type',
            old_name='gammer_low_end',
            new_name='gamer_low_end',
        ),
        migrations.RenameField(
            model_name='games_type',
            old_name='gammer_medium',
            new_name='gamer_medium',
        ),
    ]
