# Generated by Django 3.0.7 on 2021-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0008_auto_20210609_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gammes',
            old_name='high_end',
            new_name='engineer_high_end',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='low_end',
            new_name='engineer_low_end',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='medium',
            new_name='engineer_medium',
        ),
        migrations.AddField(
            model_name='gammes',
            name='gamin_high_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='gamin_low_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='gamin_medium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_high_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_low_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gammes',
            name='programmer_mediuum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
