# Generated by Django 3.2.4 on 2021-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0008_auto_20210620_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enginner_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_menimum', models.PositiveIntegerField(default=0)),
                ('engineer_avg', models.PositiveIntegerField(default=0)),
                ('engineer_medium', models.PositiveIntegerField(default=0)),
                ('engineer_max', models.PositiveIntegerField(default=0)),
                ('engineer_gpu_clock_speed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='programmer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmer_sigle_core', models.PositiveIntegerField(default=0)),
                ('programmer_multi_core', models.PositiveIntegerField(default=0)),
                ('programmer_multi_64_bit', models.PositiveIntegerField(default=0)),
                ('programmer_performance_physics', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='engineer_avg',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='engineer_gpu_clock_speed',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='engineer_max',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='engineer_medium',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='engineer_menimum',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='programmer_multi_64_bit',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='programmer_multi_core',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='programmer_performance_physics',
        ),
        migrations.RemoveField(
            model_name='games_type',
            name='programmer_sigle_core',
        ),
    ]
