# Generated by Django 3.2.4 on 2021-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0009_auto_20210620_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gamer_high_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='gamer_low_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='gamer_medium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Games_Type',
        ),
    ]
