# Generated by Django 3.0.7 on 2021-06-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0009_auto_20210610_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gammes',
            old_name='gamin_high_end',
            new_name='gammer_high_end',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='gamin_low_end',
            new_name='gammer_low_end',
        ),
        migrations.RenameField(
            model_name='gammes',
            old_name='gamin_medium',
            new_name='gammer_medium',
        ),
    ]
