# Generated by Django 3.2.4 on 2021-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0010_auto_20210620_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fps_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Enginner_Type',
        ),
        migrations.DeleteModel(
            name='programmer_Type',
        ),
    ]
