# Generated by Django 3.0.7 on 2021-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0011_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='li',
            field=models.CharField(default='ajm', max_length=100),
            preserve_default=False,
        ),
    ]
