# Generated by Django 3.2.4 on 2021-06-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0012_fps_numbers_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='fps_numbers',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tech_Parts.type'),
        ),
    ]
