# Generated by Django 3.0.7 on 2021-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0013_auto_20210611_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
