# Generated by Django 3.2.4 on 2021-06-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0013_fps_numbers_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fps_numbers',
            name='type',
        ),
        migrations.AddField(
            model_name='fps_numbers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tech_Parts.category'),
        ),
    ]
