# Generated by Django 3.2.4 on 2021-07-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0016_auto_20210709_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tech_Parts.product_filter'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
