# Generated by Django 3.0.7 on 2021-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0017_auto_20210612_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tech_Parts.Type'),
        ),
    ]
