# Generated by Django 3.2.4 on 2021-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0017_alter_product_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
