# Generated by Django 3.0.7 on 2021-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0018_auto_20210612_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(default='asd', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(default='asd', max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
