# Generated by Django 3.0.7 on 2021-06-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_Parts', '0019_auto_20210612_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
